# Data sources


## Requirement 
Write a draft of the [Data Sources chapter](https://edav.info/project#report-format). \ 

Describe the data sources: who is responsible for collecting the data? How is it collected? If there were a choice of options, explain how you chose. \ 

Provide some basic information about the dataset: types of variables, number of records, etc. Describe any issues / problems with the data, either known or that you discover. (suggested: approximately 1 page)

## Country Policy Orders
*Data Source*: 
https://healthdata.gov/dataset/covid-19-state-and-county-policy-orders 

### Description 
This is a federal government website managed by the U.S. Department of Health & Human Services. This data is a manually curated dataset that provides a standardized view into state and county policy orders (executive orders, ordinances, etc.) from the following sources:
BU COVID-19 State Policy Database - Raifman J, Nocka K, Jones D, Bor J, Lipson S, Jay J, and Chan P. (2020). "COVID-19 US state policy database."
wikidata - Stay At Home Policies Queried from WikiData. \

Manual curation by a dedicated group of Virtual Student Federal Service Interns - Summer 2020: T Adler, J Bastian, L Beckett, M Cohen, K Honey, C Kennedy, E Nudell. \ 

We chose this dataset over the BU google form linked in the sources because this dataset is much more consolidated. In addition, the website seems more reputable because it is from the government.

### Basic Information about Dataset: 

The dataset has categories: State, county, zip code, policy level, date, start stop, comments, source, total phases. There are 3507 instances. The details are as below taken from their dictionary (https://healthdata.gov/covid-19-state-and-county-policy-orders-data-dictionary): \ 

state_id (string): The two digit state code for the policy change
county (optional string): The county name where the policy change was implemented. Optional due to counties occasionally implementing their own policies.

fips_code (string): A list of fips codes where the policy change is occurring. This is the authoritative column for where a county policy change occurs.
policy_level (string): Whether the policy is a state of county-level policy. Either “state” or “county.”

date (date, formatted YYYY-MM-dd): The date of the policy. Please note that there is also a start and stop column, to indicate whether this date is for the beginning or end of the policy.

policy_type (string): The “type” of policy this in. Generically fitted in to many categories including Gym policies, Food and Drink policies, Stay at Home policies, and more.

start_stop (string): Either “start” or “stop” Indicating whether this entry is for the beginning or end of a policy, respectively.

comments (string): Details about the policies. In some cases, simply a link to a website with more information.

source (string): Where this policy comes from. Either BU COVID-19 Policy Database, Wikidata, manual (no source), or sip_submission_form (with source website URL).

total_phases (integer): As some states shifted to reopening policies, this column captures the number of phases of reopening that were expected.

*Issues about data*: This dataset pulls from many different sources. Hence, there are some missing values because some instances only have information about states in general rather than counties. 

## Hospitalization Data
*Data Source*: 
https://healthdata.gov/dataset/covid-19-estimated-patient-impact-and-hospital-capacity-state \ 

https://healthdata.gov/dataset/covid-19-reported-patient-impact-and-hospital-capacity-state

### Description 

This is a federal government website managed by the U.S. Department of Health & Human Services. The following dataset provides state-aggregated data for hospital utilization. These are derived from reports with facility-level granularity across two main sources: (1) HHS TeleTracking, and (2) reporting provided directly to HHS Protect by state/territorial health departments on behalf of their healthcare facilities. The file will be updated daily and provides the latest values reported by each facility within the last four days. This allows for a more comprehensive picture of the hospital utilization within a state by ensuring a hospital is represented, even if they miss a single day of reporting. \ 

We chose this dataset because it is from a very official source and is consolidated rather than its sources.

### Basic Information on this dataset: 

They are all numerical values. Some percentages and some numbers. There are 60 different columns and 54 instances. Details of all the columns are listed in this dictionary
(https://healthdata.gov/covid-19-reported-patient-impact-and-hospital-capacity-state-data-dictionary) Some examples are listed below:

state: The two digit state code

critical_staffing_shortage_today_yes: Number of hospitals reporting a critical staffing shortage today in this state.

hospital_onset_covid: Total current inpatients with onset of suspected or laboratory-confirmed COVID-19 fourteen or more days after admission for a condition other than COVID-19 in this state.

previous_day_admission_adult_covid_confirmed: Number of patients who were admitted to an adult inpatient bed on the previous calendar day who had confirmed COVID-19 at the time of admission in this state

staffed_adult_icu_bed_occupancy: Reported total number of staffed inpatient adult ICU beds that are occupied in this state

total_adult_patients_hospitalized_confirmed_and_suspected_covid_coverage: Number of hospitals reporting

total_staffed_adult_icu_beds: Reported total number of staffed inpatient adult ICU beds in this state

inpatient_beds_utilization: Percentage of inpatient beds that are being utilized in this state. This number only accounts for hospitals in the state that report both "inpatient_beds_used" and "inpatient_beds" fields.

inpatient_bed_covid_utilization_coverage: Number of hospitals reporting both "inpatient_beds_used_covid" and "inpatient_beds".

adult_icu_bed_covid_utilization: Percentage of total staffed adult ICU beds currently utilized by patients who have suspected or confirmed COVID-19 in this state. This number only accounts for hospitals in the state that report both "staffed_icu_adult_patients_confirmed_and_suspected_covid" and "total_staffed_adult_icu_beds" fields.

reporting_cutoff_start: Look back date start - The latest reports from each hospital is summed for this report starting with this date.

*Issues with data*: According to the data source no statistical analysis is applied to account for non-response and/or to account for missing data. Otherwise, we do not see major issues.
 
 
## Restaurant data 
*Data source*:
https://www.opentable.com/state-of-industry

### Description 
The data indexes two things. \ 
First, the overall impact of Covid 19 on the industry by showing year-over-year seated diners at a sample of restaurants on the OpenTable network across all channels: online reservations, phone reservations, and walk-ins. For year-over-year comparisons by day, we compare to the same day of the week from the same week in the previous year. For example, we’d compare Tuesday of week 11 in 2020 to Tuesday of week 11 in 2019. Only states or metros with 50+ restaurants on the OpenTable network for 2019 or 2020 are included in the sample. To better reflect the state of the industry overall, this dataset is based on a sample of approximately 20,000 restaurants that provide OpenTable with information on all of their inventory. This sample of restaurants typically accounts for a majority of our seated online reservations.\ 

Second, a comparison of year-over-year seated covers to demonstrate where we are seeing recovery start to take shape. This table shows year-over-year seated covers across all channels at only the restaurants that have chosen to reopen in a given market. As an example, if there were 50 seated covers in restaurants that have recently reopened in a given locale on May 11, 2019 and on the same day in 2020 there was 1, then 2% will be displayed. For this chart, only markets with 500+ restaurants on OpenTable of which 10%+ are accepting online reservations are included.
 
## Airlines Data 
*Data source*:
https://www.bts.gov/data-spotlight/airlines-july-operations

### Description 
This airlines data is from the Bureau of Transportation Statistics. The BTS is part of the Department of Transportation and is the main source of data on many different transportation factors such as commercial aviation, transportation economics, and freight activity. The data provided on this website is collected from the Bureau’s National Transportation Library, which contains many different publications and information about the transportation community. We chose this dataset because it provides valuable information on how the airline community was affected by the oncoming of the now widespread pandemic, Covid-19. \

### Basic Information about Dataset: 
 
year(int) - year of flight <br>
month(string) - month of flight <br>
Total Domestic Flights Operated(int) - total number of flights operated that month/year <br>
airline(string) - airline brand <br> 
 
Issues about dataset: Since there is limited information in this dataset, we will have to manipulate some variables using the information we have to analyze the data further and make stronger conclusions. Additional variables will include numerical variables such as the percent change in number of flights from each month in 2019 and 2020.  
