# Missing values

Describe any patterns you discover in missing values.

## Country Policy Orders: 
There are a few missing values county, zip_code, and total phases. This is because some states do not have details about counties. Hence there is no zip code and country details. In addition, most instances do not have total phases.

## Hospitalization: 
There are some 0 values that may be missing values in our dataset.

## Airlines Covid Data: 
There are no values missing in our dataset. The only "missing values" we had were those in the year column. The way the data was initially presented in the table, one year was written in the year column on the first row for the whole year, meaning for the next 12 rows, representing a month per row. In order to make our data more understandable and usable, such that we would not have to hard code any data, we added values to the year column, instead of leaving it blank, such that we would have a full dataset to work with. For example, instead of having only 2019 in the first row under the year column, we added 2019 to the rest of the rows until December in the year column, such that we would have a full dataset, making it easier to classify and facet data if necessary. 

## Restaurant data: 
There are many missing values in the dataset before May 2020. We also need to extract data for US.

