# Results
This is results.

```{r}
library(tidyverse)
library(choroplethr)
library(ggplot2)
library(USAboundaries)
library(plotly)
library(readxl)
```

## Covid Cases
```{r}
#data process
# prepare population per states data
df_ppl <- read_excel("./data/nst-est2019-01.xlsx", range = c("A10:M60"),
                      col_names = c("geographic_area", "ppl2000","ppl2000est","0","1","2","3","4","5","6","7","8","ppl2019")) %>% 
  mutate(state = substring(geographic_area,2)) %>% 
  select("state","ppl2019")

# prepare covid cases df
df_case = read.csv("./data/us-states.csv") 


df_total_cases <-  df_case %>% 
  filter(date == "2020-11-29") 
df_total_cases <-  df_total_cases %>% 
  merge(x = df_total_cases , y=USAboundaries :: state_codes, by.x="state", by.y = "state_name")
df_total_cases <-  df_total_cases %>% 
  merge(x = df_total_cases , y=df_ppl, by.x="state", by.y = "state") %>% 
  mutate(case_ppl = cases/ppl2019) %>% 
  mutate(case_ppl_log = log(cases/ppl2019)) %>%
  mutate(case_log = log(cases))

df_total_cases$case_ppl <-  round(df_total_cases$case_ppl, 3)

df_total_cases$hover <- with(df_total_cases, paste(state, '<br>', "Covid cases",cases,"<br>",
                                                   "Covid cases per capita",case_ppl))
                   
```   
### Covid Maps
```{r}
# give state boundaries a white border
l <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)


fig <- plot_geo(df_total_cases, locationmode = 'USA-states')

fig2 <- fig %>% add_trace(
    z = ~cases, text = ~hover, locations = ~state_abbr,
    color = ~cases, colors = 'Reds'
  )
fig2 <- fig2 %>% colorbar(title = "number of cases")
fig2 <- fig2 %>% layout(
    title = 'Positive cases of coronavirus in the United States<br>(Hover for breakdown)',
    geo = g
  )

fig2

```


```{r}
fig1 <- fig %>% add_trace(
    z = ~case_ppl, text = ~hover, locations = ~state_abbr,
    color = ~case_ppl*100, colors = 'Reds'
  )
fig1 <- fig1 %>% colorbar(title = "number cases per capita")
fig1 <- fig1 %>% layout(
    title = 'Positive cases of coronavirus per capita in the United States<br>(Hover for breakdown)',
    geo = g
  )

fig1
```



## Covid Time serires



### Covid19 Cases in Time Series
```{r}
#data process, us_cases1 is the overall us cases per day
us_cases1 <- df_case  %>% 
  count(date,wt = cases,name = "total_cases") %>% 
  mutate(date = as.Date(date)) %>% 
  mutate(new_cases = (c(1,diff(total_cases))))
```

```{r}
ggplot(us_cases1,aes(x=date,y=total_cases)) +
  geom_line(color="#69b3a2") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b")+
  theme_light()+
  ggtitle("Cumulative Covid19 Cases in the US")
```

```{r}
ggplot(us_cases1,aes(date,new_cases)) +
  geom_line(color="#69b3a2") + 
  geom_smooth(method = "loess", se = FALSE,span=0.2, lwd = 0.8) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b")+
  theme_light()+
  ylab("daily increase")
  ggtitle("Daily New Covid19 Cases in the US")
```

## Hospital 

## Covid Impact on Airlines: 

## Covid Impact on Restaurants: