# Interactive component

<script src="https://d3js.org/d3.v6.js"></script>

<button onclick="change(data2019)">Travel in 2019</button>
<button onclick="change(data2020)">Travel in 2020</button>

<h3>Total Flights in a Given Year</h3>

<paragraph>Click on a button to see the pattern of the total number of flights taken in a given year. What pattern do you notice between the years of 2019 and 2020?</paragraph>

<div id="plot"></div>

<script>
//Create Line Graph for Airline Data 
var margin = {top: 20, right: 20, bottom: 50, left: 70},
    width = 600 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

var svg = d3.select("div#plot")
    .append("svg")
          .attr("width", 600)
          .attr("height", 500)
    .append("g")
          .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");
          
var data2019 = [
   {month: 1, tot_flight: 619099},
   {month: 2, tot_flight: 564614},
   {month: 3, tot_flight: 675659}, 
   {month: 4, tot_flight: 652533}, 
   {month: 5, tot_flight: 680165}, 
   {month: 6, tot_flight: 679802}, 
   {month: 7, tot_flight: 702876}
];

var data2020 = [
   {month: 1, tot_flight: 652140},
   {month: 2, tot_flight: 617008},
   {month: 3, tot_flight: 582998}, 
   {month: 4, tot_flight: 194390}, 
   {month: 5, tot_flight: 180151}, 
   {month: 6, tot_flight: 236234}, 
   {month: 7, tot_flight: 367933}
];
          
var xScale = d3.scaleBand().range([0, width]);
        
var yScale = d3.scaleLinear().range([height, 0]);
    
var xAxis = d3.axisBottom(xScale);
svg.append("g")
  .attr("transform", "translate(0," + height + ")")
  .attr("class","myXaxis");
  
svg.append("text")             
      .attr("transform",
            "translate(" + (width/2) + " ," + 
                           (height + margin.top + 20) + ")")
      .style("text-anchor", "middle")
      .text("Month(in number)");
  
var yAxis = d3.axisLeft(yScale);
svg.append("g")
  .attr("class","myYaxis");
  
svg.append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", 0 - margin.left)
      .attr("x",0 - (height / 2))
      .attr("dy", "1em")
      .style("text-anchor", "middle")
      .text("Total Flights");

function change(data){

  xScale.domain(d3.range(1, data.length+1));
  svg.selectAll(".myXaxis").transition()
    .duration(3000)
    .call(xAxis);

  yScale.domain([d3.min(data2020, 
  function(d) { return d.tot_flight - 100000  }),
  d3.max(data2019, function(d){return d.tot_flight + 10000}) ]);
  svg.selectAll(".myYaxis").transition()
    .duration(3000)
    .call(yAxis);

  var update = svg.selectAll(".lineChange")
  .data([data], function(d){ return d.month });

  update.enter()
    .append("path")
    .attr("class","lineChange")
    .merge(update)
    .transition()
    .duration(3000)
    .attr("d", d3.line()
      .x(function(d) { return xScale(d.month); })
      .y(function(d) { return yScale(d.tot_flight); }))
      .attr("fill", "none")
      .attr("stroke", "teal")
      .attr("stroke-width", 3);
    
}
    
change(data2019);
  
</script>

<paragraph>From this graph, we can clearly see a big drop in flights from March to April of 2020. One can assume from this drop that the pandemic most likely played a role in the decrease of flights. Around May, the number of flights slowly start to increase, but not to the level that it was at the beginning of the year, as can be seen by the comparison to the flights taken in May of 2019. Even though flight frequency increased, it is still not even half as close to the regular frequency of flights.</paragraph> 