--- 
title: "Covid Impact"
author: "Run Zhang, Miranda Zhou, Mohan Duan, Neha Pusarla"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Around March of 2020, a global pandemic affected the lives of millions all over the world. This disease caused restaurants to shut down, encouraged travel bans, empty the streets of the cities, increased hospitalization, and many other factors. Everyone's lives changed without a warning, and there was no vaccine to change the situation that was the coronavirus. While the whole world went into lockdown, many people's mental health was affected as well as their physical health. The stock market fluctuated, and many were laid off or put out of a job, leaving them to struggle to find food and shelter at a time where these fundamentals were so crucial. Overall, the whole world was heavily impacted. Our main goal in studying this topic is to examine its impact on different industries due to the pandemic. We are asking four main questions, the first being how did the pandemic impact travel and the airline industry? How did the restaurant industry change? Do health mandates help curb the spread of Covid-19? For example, wearing masks and social distancing? What was the impact on hospital hours and the number of beds available? All of these questions are important in determining the role that the coronavirus played in the country's life, and we want to provide insights that can visualize the impact for everyone. People can understand the effect more clearly, and use this information to determine how careful they want to be during this time period. 

